module.exports = require('../../../utils/makeMapping')([
  'circle',
  'displayShape',
  'hexagon',
  'oval',
  'parallelogramLeft',
  'parallelogramRight',
  'rectangle',
  'rectangleOval',
  'rhombicRectangle',
  'rhombus',
  'trapezium',
  'trapeziumReverse',
  'triangle',
  'wavyBottomRectangle',
  'wavyRectangle',
])
